### ISSUE TITLE
Dimensions/size issues

### ISSUE THREAD

**Issue by miredirex** [DmitriyKhalturin/custom-card-view#5]
- `android:layout_height="wrap_content"` behaves weird if applied to the custom CardView
![image](https://user-images.githubusercontent.com/35534057/94687317-c5fff200-0334-11eb-8d6f-d2e8263edf2c.png)
This card actually has a green background but `wrap_content` turns it to white (?)
 - If the card has `cardCornerRadius` applied, then its height is also determined by its corner radius and, for example, setting `layout_height` to 1dp does nothing

**Comment by DmitriyKhalturin** [comment]
Fixed in v1.0.2
1. Background color with width CardView equal `wrap_content`.
2. `minHeight` equal `2 * cardCornerRadius` and `minWidth` consider horizontal shadow offset.
